// Vietnam provinces/cities data
export const provinces = [
  { code: "01", name: "Hà Nội" },
  { code: "02", name: "Hà Giang" },
  { code: "04", name: "Cao Bằng" },
  { code: "06", name: "Bắc Kạn" },
  { code: "08", name: "Tuyên Quang" },
  { code: "10", name: "Lào Cai" },
  { code: "11", name: "Điện Biên" },
  { code: "12", name: "Lai Châu" },
  { code: "14", name: "Sơn La" },
  { code: "15", name: "Yên Bái" },
  { code: "17", name: "Hòa Bình" },
  { code: "19", name: "Thái Nguyên" },
  { code: "20", name: "Lạng Sơn" },
  { code: "22", name: "Quảng Ninh" },
  { code: "24", name: "Bắc Giang" },
  { code: "25", name: "Phú Thọ" },
  { code: "26", name: "Vĩnh Phúc" },
  { code: "27", name: "Bắc Ninh" },
  { code: "30", name: "Hải Dương" },
  { code: "31", name: "Hải Phòng" },
  { code: "33", name: "Hưng Yên" },
  { code: "34", name: "Thái Bình" },
  { code: "35", name: "Hà Nam" },
  { code: "36", name: "Nam Định" },
  { code: "37", name: "Ninh Bình" },
  { code: "38", name: "Thanh Hóa" },
  { code: "40", name: "Nghệ An" },
  { code: "42", name: "Hà Tĩnh" },
  { code: "44", name: "Quảng Bình" },
  { code: "45", name: "Quảng Trị" },
  { code: "46", name: "Thừa Thiên Huế" },
  { code: "48", name: "Đà Nẵng" },
  { code: "49", name: "Quảng Nam" },
  { code: "51", name: "Quảng Ngãi" },
  { code: "52", name: "Bình Định" },
  { code: "54", name: "Phú Yên" },
  { code: "56", name: "Khánh Hòa" },
  { code: "58", name: "Ninh Thuận" },
  { code: "60", name: "Bình Thuận" },
  { code: "62", name: "Kon Tum" },
  { code: "64", name: "Gia Lai" },
  { code: "66", name: "Đắk Lắk" },
  { code: "67", name: "Đắk Nông" },
  { code: "68", name: "Lâm Đồng" },
  { code: "70", name: "Bình Phước" },
  { code: "72", name: "Tây Ninh" },
  { code: "74", name: "Bình Dương" },
  { code: "75", name: "Đồng Nai" },
  { code: "77", name: "Bà Rịa - Vũng Tàu" },
  { code: "79", name: "TP. Hồ Chí Minh" },
  { code: "80", name: "Long An" },
  { code: "82", name: "Tiền Giang" },
  { code: "83", name: "Bến Tre" },
  { code: "84", name: "Trà Vinh" },
  { code: "86", name: "Vĩnh Long" },
  { code: "87", name: "Đồng Tháp" },
  { code: "89", name: "An Giang" },
  { code: "91", name: "Kiên Giang" },
  { code: "92", name: "Cần Thơ" },
  { code: "93", name: "Hậu Giang" },
  { code: "94", name: "Sóc Trăng" },
  { code: "95", name: "Bạc Liêu" },
  { code: "96", name: "Cà Mau" },
];

// Sample districts for popular cities
export const districts: Record<string, { code: string; name: string }[]> = {
  "79": [ // TP. HCM
    { code: "760", name: "Quận 1" },
    { code: "761", name: "Quận 12" },
    { code: "764", name: "Gò Vấp" },
    { code: "765", name: "Bình Thạnh" },
    { code: "766", name: "Tân Bình" },
    { code: "767", name: "Tân Phú" },
    { code: "768", name: "Phú Nhuận" },
    { code: "769", name: "Thủ Đức" },
    { code: "770", name: "Quận 3" },
    { code: "771", name: "Quận 10" },
    { code: "772", name: "Quận 11" },
    { code: "773", name: "Quận 4" },
    { code: "774", name: "Quận 5" },
    { code: "775", name: "Quận 6" },
    { code: "776", name: "Quận 8" },
    { code: "777", name: "Bình Tân" },
    { code: "778", name: "Quận 7" },
  ],
  "01": [ // Hà Nội
    { code: "001", name: "Ba Đình" },
    { code: "002", name: "Hoàn Kiếm" },
    { code: "003", name: "Tây Hồ" },
    { code: "004", name: "Long Biên" },
    { code: "005", name: "Cầu Giấy" },
    { code: "006", name: "Đống Đa" },
    { code: "007", name: "Hai Bà Trưng" },
    { code: "008", name: "Hoàng Mai" },
    { code: "009", name: "Thanh Xuân" },
    { code: "016", name: "Sóc Sơn" },
    { code: "017", name: "Đông Anh" },
    { code: "018", name: "Gia Lâm" },
    { code: "019", name: "Nam Từ Liêm" },
    { code: "020", name: "Thanh Trì" },
    { code: "021", name: "Bắc Từ Liêm" },
    { code: "250", name: "Mê Linh" },
    { code: "268", name: "Hà Đông" },
  ],
  "48": [ // Đà Nẵng
    { code: "490", name: "Liên Chiểu" },
    { code: "491", name: "Thanh Khê" },
    { code: "492", name: "Hải Châu" },
    { code: "493", name: "Sơn Trà" },
    { code: "494", name: "Ngũ Hành Sơn" },
    { code: "495", name: "Cẩm Lệ" },
    { code: "497", name: "Hòa Vang" },
  ],
};

// Sample wards
export const wards: Record<string, { code: string; name: string }[]> = {
  "760": [ // Quận 1
    { code: "26734", name: "Tân Định" },
    { code: "26737", name: "Đa Kao" },
    { code: "26740", name: "Bến Nghé" },
    { code: "26743", name: "Bến Thành" },
    { code: "26746", name: "Nguyễn Thái Bình" },
    { code: "26749", name: "Phạm Ngũ Lão" },
    { code: "26752", name: "Cầu Ông Lãnh" },
    { code: "26755", name: "Cô Giang" },
    { code: "26758", name: "Nguyễn Cư Trinh" },
    { code: "26761", name: "Cầu Kho" },
  ],
  "765": [ // Bình Thạnh
    { code: "27055", name: "Phường 1" },
    { code: "27058", name: "Phường 2" },
    { code: "27061", name: "Phường 3" },
    { code: "27064", name: "Phường 11" },
    { code: "27067", name: "Phường 12" },
    { code: "27070", name: "Phường 13" },
    { code: "27073", name: "Phường 14" },
    { code: "27076", name: "Phường 15" },
    { code: "27079", name: "Phường 17" },
    { code: "27082", name: "Phường 19" },
    { code: "27085", name: "Phường 21" },
    { code: "27088", name: "Phường 22" },
    { code: "27091", name: "Phường 24" },
    { code: "27094", name: "Phường 25" },
    { code: "27097", name: "Phường 26" },
    { code: "27100", name: "Phường 27" },
    { code: "27103", name: "Phường 28" },
  ],
  "001": [ // Ba Đình
    { code: "00001", name: "Phúc Xá" },
    { code: "00004", name: "Trúc Bạch" },
    { code: "00007", name: "Vĩnh Phúc" },
    { code: "00010", name: "Cống Vị" },
    { code: "00013", name: "Liễu Giai" },
    { code: "00016", name: "Nguyễn Trung Trực" },
    { code: "00019", name: "Quán Thánh" },
    { code: "00022", name: "Ngọc Hà" },
    { code: "00025", name: "Điện Biên" },
    { code: "00028", name: "Đội Cấn" },
    { code: "00031", name: "Ngọc Khánh" },
    { code: "00034", name: "Kim Mã" },
    { code: "00037", name: "Giảng Võ" },
    { code: "00040", name: "Thành Công" },
  ],
};

export function getDistrictsByProvince(provinceCode: string) {
  return districts[provinceCode] || [];
}

export function getWardsByDistrict(districtCode: string) {
  return wards[districtCode] || [];
}
